### ISSUE TITLE
WebP support not working?

### ISSUE THREAD

**Issue by hughstephens** [DarthSim/imgproxy#127] opened 2019-01-11 08:44 UTC
Hi team

When I'm trying to generate a thumbnail/resize a WEBP file (example https://s3.amazonaws.com/sked-customer-uploads/564a433accc7c331440002f9/83324ed7d9f4291d49e9bba969687b66.orig.jpg - ignore JPG extension…), I'm getting an invalid image error - but according to the docs it should accept it?

Thanks
hugh

**Comment by DarthSim** [comment] 2019-01-11 10:56
Hi,

WebP support isn't completely broken, but there is definitely a problem with this exact image. Go says `non-Alpha VP8X is not implemented`, it's a problem with standard Go WebP package that I use for image type detection. I'll try to bypass this.

**Comment by hughstephens** [comment] 2019-01-11 23:33
Thanks @DarthSim – good to know it's just something strange with this file. Nothing too drastic as it actually demonstrated we had a bug anyway (we should've converted to JPG on our side regardless).

Thanks for imgproxy btw! Great tool.

**Comment by DarthSim** [comment] 2019-01-15 09:50
The issue is fixed in v2.1.5

**Closed by DarthSim** 2019-01-15 09:50 UTC
Labels: bug
